
// Objective-C API for talking to the following Go packages
//
//	github.com/darmaproject/darmasuite/utilities/appwallet
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Appwallet_FRAMEWORK_H__
#define __Appwallet_FRAMEWORK_H__

#include "Appwallet.objc.h"
#include "Universe.objc.h"

#endif
