// Objective-C API for talking to github.com/darmaproject/darmasuite/utilities/appwallet Go package.
//   gobind -lang=objc github.com/darmaproject/darmasuite/utilities/appwallet
//
// File is generated by gobind. Do not edit.

#ifndef __Appwallet_H__
#define __Appwallet_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class AppwalletAppWalletError;
@class AppwalletAppWalletPingResult;
@class AppwalletAppWalletTransferTX;
@class AppwalletMobileWallet;
@class AppwalletMobileWalletAddress;
@class AppwalletTxMerge;
@class AppwalletWalletBackupInfo;
@class AppwalletWalletKeys;
@class AppwalletWalletStats;
@protocol AppwalletAppWalletStats;
@class AppwalletAppWalletStats;

@protocol AppwalletAppWalletStats <NSObject>
- (void)dumpWalletStats:(NSString* _Nullable)stats;
@end

@interface AppwalletAppWalletError : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long errCode;
@property (nonatomic) NSString* _Nonnull errMsg;
@end

@interface AppwalletAppWalletPingResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long status;
@property (nonatomic) int64_t delay;
@property (nonatomic) int64_t height;
@property (nonatomic) int64_t topoHeight;
@property (nonatomic) int64_t score;
@end

@interface AppwalletAppWalletTransferTX : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field AppWalletTransferTX.Transfer_fee with unsupported type: uint64

// skipped field AppWalletTransferTX.Transfer_amount with unsupported type: uint64

// skipped field AppWalletTransferTX.Transfer_change with unsupported type: uint64

// skipped field AppWalletTransferTX.Transfer_inputs_sum with unsupported type: uint64

@property (nonatomic) NSString* _Nonnull transfer_txid;
@property (nonatomic) NSString* _Nonnull transfer_txhex;
@end

@interface AppwalletMobileWallet : NSObject <goSeqRefInterface, AppwalletAppWalletStats> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
@property (nonatomic) NSString* _Nonnull fileName;
// skipped field MobileWallet.Wallet with unsupported type: interface{}

@property (nonatomic) id<AppwalletAppWalletStats> _Nullable appWalletStats;
// skipped field MobileWallet.QuitChan with unsupported type: chan int

@property (nonatomic) BOOL isSync;
- (NSString* _Nonnull)backup_WalletFile:(NSString* _Nullable)basedir password:(NSString* _Nullable)password;
- (BOOL)change_Password:(NSString* _Nullable)password;
- (BOOL)check_Password:(NSString* _Nullable)password;
- (BOOL)close_Encrypted_Wallet;
- (BOOL)create_Encrypted_Wallet:(NSString* _Nullable)filename password:(NSString* _Nullable)password;
- (BOOL)create_Encrypted_Wallet_SpendKey:(NSString* _Nullable)filename password:(NSString* _Nullable)password spendkey:(NSString* _Nullable)spendkey;
- (BOOL)create_Encrypted_Wallet_ViewOnly:(NSString* _Nullable)filename password:(NSString* _Nullable)password viewkey:(NSString* _Nullable)viewkey;
- (void)dumpWalletStats:(NSString* _Nullable)stats;
- (NSString* _Nonnull)generate_Intergrated_Address:(long)payment_id_len;
- (NSString* _Nonnull)get_Daemon_Address;
- (int64_t)get_Delay_Sync;
- (float)get_Fee_Multiplier;
- (NSString* _Nonnull)get_Keys:(NSString* _Nullable)password;
- (long)get_Mixin;
- (NSString* _Nonnull)get_Seeds:(NSString* _Nullable)password;
- (NSString* _Nonnull)get_Transfers:(BOOL)in_ out_:(BOOL)out_ max_height_str:(NSString* _Nullable)max_height_str limit_str:(NSString* _Nullable)limit_str;
- (NSString* _Nonnull)get_Tx_Key:(NSString* _Nullable)txid;
- (NSString* _Nonnull)get_Wallet_Address;
- (NSString* _Nonnull)get_Wallet_Name;
- (BOOL)is_View_Only;
- (BOOL)open_Encrypted_Wallet:(NSString* _Nullable)filename password:(NSString* _Nullable)password;
- (BOOL)recovery_Encrypted_Wallet:(NSString* _Nullable)filename password:(NSString* _Nullable)password electrum_seed:(NSString* _Nullable)electrum_seed;
- (void)rescan_From_Height;
- (NSString* _Nonnull)send_Raw_Transaction:(NSString* _Nullable)txraw;
- (BOOL)set_Daemon_Address:(NSString* _Nullable)endpoints;
- (int64_t)set_Delay_Sync:(int64_t)delay;
- (void)set_DumpStats_Callback:(id<AppwalletAppWalletStats> _Nullable)s;
- (float)set_Fee_Multiplier:(float)x;
- (BOOL)set_Initial_Height:(int64_t)startheight;
- (int64_t)set_Initial_Height_Default;
- (BOOL)set_Lightweight_Mode:(BOOL)lightweight;
- (long)set_Mixin:(long)mixin;
- (BOOL)set_Offline_Mode;
- (BOOL)set_Online_Mode;
- (BOOL)stop_Update_Blance;
- (NSString* _Nonnull)transfer:(NSString* _Nullable)toaddr amountstr:(NSString* _Nullable)amountstr unlock_time_str:(NSString* _Nullable)unlock_time_str payment_id:(NSString* _Nullable)payment_id mixin:(long)mixin sendtx:(BOOL)sendtx password:(NSString* _Nullable)password;
- (NSString* _Nonnull)transfer_Everything:(NSString* _Nullable)address unlock_time_str:(NSString* _Nullable)unlock_time_str payment_id_hex:(NSString* _Nullable)payment_id_hex mixin:(long)mixin sendtx:(BOOL)sendtx password:(NSString* _Nullable)password;
- (BOOL)update_Wallet_Balance;
- (NSString* _Nonnull)verify_Address:(NSString* _Nullable)address;
@end

@interface AppwalletMobileWalletAddress : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) BOOL isValid;
@property (nonatomic) BOOL isIntegratedAddress;
@property (nonatomic) NSString* _Nonnull address;
@property (nonatomic) NSString* _Nonnull paymentID;
@end

@interface AppwalletTxMerge : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@end

@interface AppwalletWalletBackupInfo : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull name;
@property (nonatomic) int64_t ctime;
@property (nonatomic) int64_t height;
@property (nonatomic) NSString* _Nonnull seeds;
@property (nonatomic) NSString* _Nonnull checkSum;
@property (nonatomic) NSString* _Nonnull signature;
@end

@interface AppwalletWalletKeys : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull spendkey_Secret;
@property (nonatomic) NSString* _Nonnull spendkey_Public;
@property (nonatomic) NSString* _Nonnull viewkey_Secret;
@property (nonatomic) NSString* _Nonnull viewkey_Public;
@end

@interface AppwalletWalletStats : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field WalletStats.Unlocked_balance with unsupported type: uint64

// skipped field WalletStats.Locked_balance with unsupported type: uint64

// skipped field WalletStats.Total_balance with unsupported type: uint64

// skipped field WalletStats.Wallet_height with unsupported type: uint64

// skipped field WalletStats.Daemon_height with unsupported type: uint64

@property (nonatomic) int64_t wallet_topo_height;
// skipped field WalletStats.Daemon_topo_height with unsupported type: uint64

@property (nonatomic) int64_t wallet_initial_height;
@property (nonatomic) BOOL wallet_available;
@property (nonatomic) BOOL wallet_complete;
@property (nonatomic) BOOL wallet_online;
@property (nonatomic) BOOL wallet_balance_changed;
@property (nonatomic) long wallet_mixin;
@property (nonatomic) double wallet_fees_multiplier;
@property (nonatomic) int64_t wallet_sync_time;
@property (nonatomic) int64_t wallet_minimum_topo_height;
@end

@interface Appwallet : NSObject
+ (long) errAgain;
+ (void) setErrAgain:(long)v;

+ (long) errBadWalletFile;
+ (void) setErrBadWalletFile:(long)v;

+ (long) errDaemonIsEmpty;
+ (void) setErrDaemonIsEmpty:(long)v;

+ (long) errDecodeData;
+ (void) setErrDecodeData:(long)v;

+ (long) errEncodeData;
+ (void) setErrEncodeData:(long)v;

+ (long) errExist;
+ (void) setErrExist:(long)v;

+ (long) errInvalidAddress;
+ (void) setErrInvalidAddress:(long)v;

+ (long) errInvalidAmount;
+ (void) setErrInvalidAmount:(long)v;

+ (long) errInvalidDaemon;
+ (void) setErrInvalidDaemon:(long)v;

+ (long) errInvalidFileName;
+ (void) setErrInvalidFileName:(long)v;

+ (long) errInvalidKeys;
+ (void) setErrInvalidKeys:(long)v;

+ (long) errInvalidPassword;
+ (void) setErrInvalidPassword:(long)v;

+ (long) errInvalidPaymentID;
+ (void) setErrInvalidPaymentID:(long)v;

+ (long) errInvalidTxid;
+ (void) setErrInvalidTxid:(long)v;

+ (long) errInvalidWalletObject;
+ (void) setErrInvalidWalletObject:(long)v;

+ (long) errIsSync;
+ (void) setErrIsSync:(long)v;

+ (long) errNotIsSync;
+ (void) setErrNotIsSync:(long)v;

+ (long) errPaswordMisMatch;
+ (void) setErrPaswordMisMatch:(long)v;

+ (long) errSuccess;
+ (void) setErrSuccess:(long)v;

+ (long) errSystemInternal;
+ (void) setErrSystemInternal:(long)v;

+ (long) errWalletBusy;
+ (void) setErrWalletBusy:(long)v;

@end

FOUNDATION_EXPORT NSString* _Nonnull AppwalletCheck_Backup_WalletFile(NSString* _Nullable backupname);

FOUNDATION_EXPORT BOOL AppwalletCreate_Encrypted_Wallet(NSString* _Nullable filename, NSString* _Nullable password);

FOUNDATION_EXPORT BOOL AppwalletCreate_Encrypted_Wallet_ViewOnly(NSString* _Nullable filename, NSString* _Nullable password, NSString* _Nullable viewkey);

FOUNDATION_EXPORT NSString* _Nonnull AppwalletDiscovery(NSString* _Nullable endpoints);

FOUNDATION_EXPORT NSString* _Nonnull AppwalletFormat_Money(NSString* _Nullable amountstr);

FOUNDATION_EXPORT NSString* _Nonnull AppwalletGetLastError(void);

// skipped function Get_Info_Request with unsupported parameter or return types


FOUNDATION_EXPORT NSString* _Nonnull AppwalletGet_Wallet_Address(NSString* _Nullable filename, NSString* _Nullable password);

FOUNDATION_EXPORT AppwalletMobileWallet* _Nullable AppwalletNewMobileWallet(void);

FOUNDATION_EXPORT NSString* _Nonnull AppwalletPing_Daemon_Address(NSString* _Nullable endpoint);

FOUNDATION_EXPORT BOOL AppwalletRecovery_Encrypted_Wallet(NSString* _Nullable filename, NSString* _Nullable password, NSString* _Nullable electrum_seed);

FOUNDATION_EXPORT BOOL AppwalletRestore_WalletFile(NSString* _Nullable backupname, NSString* _Nullable pathname, NSString* _Nullable password, int64_t start_height);

FOUNDATION_EXPORT BOOL AppwalletVerify_Amount(NSString* _Nullable amount);

@class AppwalletAppWalletStats;

@interface AppwalletAppWalletStats : NSObject <goSeqRefInterface, AppwalletAppWalletStats> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)dumpWalletStats:(NSString* _Nullable)stats;
@end

#endif
